[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pickomino-env"
version = "0.1.0"
description = "Pickomino (Heckmeck) Gymnasium environment"
readme = ""
requires-python = ">=3.9"
authors = [{ name = "Jarl,Robin,Tanja" }]
dependencies = [
  "gymnasium>=0.28",
  "numpy>=1.23",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pickomino_env*"]
